#ifndef H_MESSENGER_EVENT_TYPE
#define H_MESSENGER_EVENT_TYPE


enum class MessengerEventType
{
	CHANGE_SCENE,
	PLAYER_LOSE_LIFE,
	PLAYER_DEAD,
	COIN_INSERTED,
	PLAYER_REVIVED,
	FLOOR_MOTION_STOPPED,
	FLOOR_MOTION_RESUMED,
	POINTS_5000,
	POINTS_10000,
	POINTS_100000,
	BOSS_SPAWNED,
	GAME_WON
};


#endif // !H_MESSENGER_EVENT_TYPE
